# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          prince427/personal-cv$(tag)
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: |
          DockerHub
        repository: prince427/personal-cv
        command: push
        tags: |
          prince427/personal-cv$(tag)

    - task: CmdLine@2
      displayName: Debug
      inputs:
        script: 'docker images' 
